version: '3'
services:
    app:
        image: node
        volumes:
            - ./src:/usr/src/app
        ports:
            - 3000:3000
        working_dir: /usr/src/app
        command: 'npm run live'
    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=${PARKS_DB}
        volumes:
            - ./db:/var/lib/mysql
        ports:
            - 4306:3306